#SPDX-License-Identifier: MIT-0
---
# handlers file for node_exporter_install
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart node_exporter service
  ansible.builtin.service:
    name: node_exporter
    state: restarted