services:
  prometheus:
    environment:
      - TZ=Europe/Moscow
    image: prom/prometheus
    container_name: prometheus
    user: root
    command: '--config.file=/etc/prometheus/prometheus.yml' 
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    ports:
      - 9090:9090
    restart: always


  grafana:
    environment:
      - TZ=Europe/Moscow
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana
  
  loki:
    environment:
      - TZ=Europe/Moscow
    image: grafana/loki
    container_name: loki
    command: '-config.file=/etc/loki/local-config.yaml'
    volumes:
      - loki_data:/tmp/loki
    ports:
      - 3100:3100
    restart: always

volumes:
  prom_data:
  loki_data:
  grafana_data:
