global:
  scrape_interval: "15s"
  scrape_timeout: "10s"
scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    honor_labels: false
    honor_timestamps: true
    scheme: http
    follow_redirects: true
    body_size_limit: "0"
    static_configs:
      - targets:
          - 127.0.0.1:9090
          - 192.168.1.170:9100
