---

- name: Set timezone to Europe/Moscow
  community.general.timezone:
    name: Europe/Moscow

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - ca-certificates 
      - curl
      - software-properties-common
      - python3-docker
    state: present
    update_cache: true

- name: Create keyring directory for Docker's GPG key
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add GPG Docker key and repo
  block:
    - name: Add key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc

    - name: Add repo
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      - docker-buildx-plugin 
      - docker-compose-plugin
    state: latest
    update_cache: true

- name: Ensure docker group exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Copy docker config file
  ansible.builtin.copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart docker daemon

- name: Ensure docker engine is active
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
